### ISSUE TITLE
capistrano fails to deploy latest version

### ISSUE THREAD

**Issue by mackuba** [mackuba/sparkler#1]
Looks like Capistrano is failing in the assets precompiling task, because it expects the manifest in the old place, and latest Sprockets has moved it elsewhere... I'll have to update Capistrano, but the 2.x branch isn't maintained anymore, so I'll have to update to 3.x which changes/removes a lot of things... (Sigh, this kind of things is why I left web development :P)

**Comment by bjorn** [comment]
Is this problem related?

```
root@4004fdb2f75f:/sparkler# RAILS_ENV=production bin/rake assets:precompile
Warning: Running `gem pristine --all` to regenerate your installed gemspecs (and deleting then reinstalling your bundle if you use bundle --path) will improve the startup performance of Spring.
/var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'uglifier'. (Bundler::GemRequireError)
    from /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    from /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
    from /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
    from /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
    from /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
    from /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
    from /sparkler/config/application.rb:15:in `<top (required)>'
    from /var/lib/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:82:in `require'
    from /var/lib/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:82:in `preload'
    from /var/lib/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:143:in `serve'
    from /var/lib/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:131:in `block in run'
    from /var/lib/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `loop'
    from /var/lib/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `run'
    from /var/lib/gems/2.1.0/gems/spring-1.2.0/lib/spring/application/boot.rb:18:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from -e:1:in `<main>'
```

I do have uglifier installed through bundler:

```
root@4004fdb2f75f:/sparkler# gem list uglifier

*** LOCAL GEMS ***

uglifier (2.7.2, 2.7.0)
```

**Comment by mackuba** [comment]
Hmm, I don't think so, that one was about a missing file... Does it work if you do `bundle exec rake` instead of `bin/rake`?

**Comment by bjorn** [comment]
No, same error. Here's the Dockerfile I have so far, maybe you can spot an error there:

``` Dockerfile
FROM ubuntu:wily

RUN apt-get update && apt-get -y upgrade

RUN apt-get install -y ruby ruby-dev git build-essential
RUN gem install bundler

# Install Nginx and Passenger
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7
RUN apt-get install -y apt-transport-https ca-certificates
RUN sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger wily main > /etc/apt/sources.list.d/passenger.list'
RUN apt-get update && apt-get install -y nginx-extras passenger

RUN git clone https://github.com/mackuba/sparkler.git
RUN apt-get install -y zlib1g-dev libmysqlclient-dev

RUN cd sparkler && bundle install --without development test
```

After this, I'm trying to continue your setup instructions but running into the above error.

Thanks for any help. I'd really love to have some insight in how many people are using my application, and your solution seems to be very nice!

**Comment by mackuba** [comment]
http://stackoverflow.com/a/34578598 - maybe this?

**Comment by bjorn** [comment]
@mackuba Installing `nodejs` actually resolved my issue, thanks! Unfortunately, my next stumbling block is the database setup and configuration, so it may be a while until I have time to get this running.

**Comment by mackuba** [comment]
Fixed in the latest version (though a manual update of the Capistrano scripts to Cap 3.x format is required).
